# Author: Mazhar Ahmed, CTO, Oceanize Inc
# All rights reserved. Copyright (c) Oceanize Inc
version: '3'
services:
  flask_api:
    image: flask_api:latest
    container_name: flask_api
    restart: unless-stopped
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
      # set database, memcached etc credentials
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: ben
    volumes:
      - ./app:/app
    links:
      # network connection with these services
      - mysql
    depends_on:
      # build those images first
      - mysql
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5000:5000"

  mysql:
    container_name: db_mysql
    # let's grab from mysql 5.7 image
    image: mysql:latest
    volumes:
        # pass volume named mysql-data to mysql container
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    ports:
       - "3306:3306"
    environment:
      # credentials
      MYSQL_ROOT_PASSWORD: ben
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: ben
